# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jon-Erling Svendsen
# Description of the Site
description: Dronepilot
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/20536867/pexels-photo-20536867/free-photo-of-fredrikstad.png?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jonerlingsvendsen@gmail.com
facebook_username: Jon-Erling Svendsen
twitter_username: 
instagram_username: Jonsvee
linkedin_username: jon-erling-svendsen-2b45ba2b4
github_username:  
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Jon-Erling Svendsen
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: Hello, I am a 18 year old drone pilot that operate in the area around Fredrikstad Norway. I am very interested in learning and love working with what i enjoy. I am currently a student at Glemmen High School and a trainee at Bærum Municipality 
author-url: https://github.com/DjDoon

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
